# Generated by Django 6.0.5 on 2026-06-04 18:40

import company.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Наименование поставщика')),
                ('inn', models.CharField(max_length=12, unique=True, validators=[company.models.validate_inn], verbose_name='ИНН поставщика')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='company.company', verbose_name='Компания поставщика')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['title'],
                'unique_together': {('company', 'title')},
            },
        ),
    ]
