# Generated by Django 6.0.5 on 2026-05-19 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес склада')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='company.company', verbose_name='Компания склада')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ['address'],
            },
        ),
    ]
