# Generated by Django 6.0.5 on 2026-06-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplyproduct',
            unique_together={('supply', 'product')},
        ),
        migrations.AddIndex(
            model_name='supplyproduct',
            index=models.Index(fields=['supply', 'product'], name='supply_supp_supply__34df92_idx'),
        ),
    ]
